//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.coverviewlibrary;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.TextView;
import com.example.coverviewlibrary.R.id;
import com.example.coverviewlibrary.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class CoverView_
    extends CoverView
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public CoverView_(Context context) {
        super(context);
        init_();
    }

    public CoverView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public CoverView_(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init_();
    }

    public static CoverView build(Context context) {
        CoverView_ instance = new CoverView_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.cover_view_layout, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static CoverView build(Context context, AttributeSet attrs) {
        CoverView_ instance = new CoverView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static CoverView build(Context context, AttributeSet attrs, int defStyleAttr) {
        CoverView_ instance = new CoverView_(context, attrs, defStyleAttr);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mProgressBar = ((ProgressBar) hasViews.findViewById(id.cover_view_progressBar));
        btn_refresh = ((Button) hasViews.findViewById(id.cover_view_btn_refresh));
        mImageView = ((ImageView) hasViews.findViewById(id.cover_view_image));
        mTextView = ((TextView) hasViews.findViewById(id.cover_view_info));
        afterViews();
    }

}
